require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'

require_relative '../lib/whats_happening/version'
require_relative '../lib/whats_happening/cli'
require_relative '../lib/whats_happening/scraper'
require_relative '../lib/whats_happening/celebration'
require_relative '../lib/whats_happening/month'
require_relative '../lib/whats_happening'
